version: '3.8'

services:
  shortgen:
    build: .
    image: shortgen:latest
    container_name: shortgen
    volumes:
      # Mount input/output directories
      - ./videos:/app/videos
      - ./output:/app/output
      # Mount YouTube credentials (if using upload feature)
      - ./client_secrets.json:/app/client_secrets.json:ro
      - ./token.pickle:/app/token.pickle
    environment:
      # Optional: Set Whisper model via environment variable
      - WHISPER_MODEL=small
    command: /app/videos --output /app/output

  # Optional: GPU-enabled service (requires nvidia-docker)
  shortgen-gpu:
    build: .
    image: shortgen:latest
    container_name: shortgen-gpu
    volumes:
      - ./videos:/app/videos
      - ./output:/app/output
      # Mount YouTube credentials (if using upload feature)
      - ./client_secrets.json:/app/client_secrets.json:ro
      - ./token.pickle:/app/token.pickle
    environment:
      - WHISPER_MODEL=medium
    command: /app/videos --output /app/output --gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
